### ISSUE TITLE
Running dotadevkit

### ISSUE THREAD

**Issue by Kgauza** [ashnair1/dotadevkit#12]
Ive installed dotadevkit using anaconda on a windows machine.
Any idea how I go about running it, Ive tried running it on the CMD/anaconda prompt, it doesnt work.

How do i get it up and running. I wanna split the images and their respective annotations

**Comment by ashnair1** [comment]
You can check if dotadevkit has been successfully installed by first running dotadevkit --help

To split, images and annotations into tiles, you can run


dotadevkit split \
        ./example/ \
        ./example_split/ \
        8

**Comment by Kgauza** [comment]
I've installed it through Anaconda prompt.
When I try running it on Anaconda prompt I get the following error:

 "dotadevkit' is not recognized as an internal or external command, operable program or batch file."

**Comment by ashnair1** [comment]
By installing through Anaconda prompt, I'm assuming you already ran 'pip install dotadevkit'

If you've installed it and this error shows up, it might mean that the installation location of the package is not in your PATH. 

Try looking for the folder containing dotadevkit.exe in your system.

**Comment by Kgauza** [comment]
It is up and running now. Thank you for you much needed assistance.
