### ISSUE TITLE
import _polyiou ModuleNotFoundError: No module named ‘_polyiou‘

### ISSUE THREAD

**Issue by MFalam** [ashnair1/dotadevkit#17]
I have a big problem and already tried many ways to find a solution for this error, but it still remains in my codes.
I am trying to reimplement the " BBAVectors-Oriented-Object-Detection" and firstly used "DOTA_devkit" but always facing 
    "import _polyiou ModuleNotFoundError: No module named ‘_polyiou‘" 
Then I switched to "dotadevkit" but still I have the same issue. The "dotadevkit" works fine for the other tasks.

![BBA-1](https://user-images.githubusercontent.com/86053332/122525103-79d41980-d04b-11eb-91f8-e5c4fb0c0dc8.png)

I use Python 3.6.6 on Ubuntu.

I wish to receive a suggestion to solve this problem.

**Comment by ashnair1** [comment]
You need to import polyiou from dotadevkit

```
>>> from dotadevkit import polyiou
>>> polyiou
<module 'dotadevkit.polyiou' from '/home/ashwin/anaconda3/lib/python3.7/site-packages/dotadevkit/polyiou/__init__.py'>
```

**Comment by MFalam** [comment]
> You need to import polyiou from dotadevkit
> 
> ```
> >>> from dotadevkit import polyiou
> >>> polyiou
> <module 'dotadevkit.polyiou' from '/home/ashwin/anaconda3/lib/python3.7/site-packages/dotadevkit/polyiou/__init__.py'>
> ```

Many thanks for this point.

I face another issue with the dotadevkit. 
`attributeerror: module 'dotadevkit.polyiou' has no attribute 'VectorDouble'`

![BBA-3](https://user-images.githubusercontent.com/86053332/122540144-e99dd080-d05a-11eb-87d6-2a5af56952bc.png)


May please suggest a solution.

**Comment by ashnair1** [comment]
Sorry you need to import it like this for getting access to the methods

```
from dotadevkit.polyiou import polyiou
```

**Comment by ashnair1** [comment]
It looks like you're using both the original DOTA_Devkit and this repo (dotadevkit). This is not necessary. Another user previously wanted to use this dotadevkit with the BBAVectors repo. You can view that issue [here](https://github.com/ashnair1/dotadevkit/issues/7#issuecomment-730607025).

**Comment by MFalam** [comment]
> It looks like you're using both the original DOTA_Devkit and this repo (dotadevkit). This is not necessary. Another user previously wanted to use this dotadevkit with the BBAVectors repo. You can view that issue [here](https://github.com/ashnair1/dotadevkit/issues/7#issuecomment-730607025).

Many thanks for the help.
