### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.dotadevkit.ResultMerge_multi_process'

### ISSUE THREAD

**Issue by s-s-wang** [ashnair1/dotadevkit#7]
in the dotadevkit, don't find ResultMerge_multi_process

**Comment by ashnair1** [comment]
I don't think you're using `dotadevkit` correctly. The correct usage for the merge function has been documented [here](https://github.com/ashnair1/dotadevkit#merge).

For reference, this package only uses the multiprocessing versions of ResutMerge and Split from the original DOTA Devkit. That is to say this [file](https://github.com/ashnair1/dotadevkit/blob/master/dotadevkit/ops/ResultMerge.py) is `ResultMerge_multi_process`. It's just been renamed.

**Comment by s-s-wang** [comment]
> 
> 
> I don't think you're using `dotadevkit` correctly. The correct usage for the merge function has been documented [here](https://github.com/ashnair1/dotadevkit#merge). You just need to pass in 3 arguments:
> 
>     1. The src directory of tile detections
> 
>     2. The destination directory to save the merged detections.
> 
>     3. Number of processes you want to use
> 
> 
> For reference, this package only uses the multiprocessing versions of ResutMerge and Split from the original DOTA Devkit. That is to say this [file](https://github.com/ashnair1/dotadevkit/blob/master/dotadevkit/ops/ResultMerge.py) is `ResultMerge_multi_process`. It's just been renamed.

Thank you very much. But it show "No module named 'datasets.DOTA_devkit'", when executive the train command

**Comment by ashnair1** [comment]
The dotadevkit does not have a train command just like the original DOTA Devkit did not have a train command.

The dev kit has 3 main functions:

1. Split the training data (images and labels) into tiles to train your model.
2. Merge the tiled results of your model.
3. Evaluate the merged detections against the val/test data and output a score.

**Comment by s-s-wang** [comment]
Thanks for you reply. I'm executing train commands in the BBAVectors-Oriented-Object-Detection-master directory. It show "ModuleNotFoundError: No module named 'datasets.dotadevkit.ResultMerge_multi_process'". If I use this new dotadevkit, can I remove the orignal DOTA_devkit?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ashnair1/dotadevkit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 晚上6:40
收件人:&nbsp;"ashnair1/dotadevkit"<dotadevkit@noreply.github.com&gt;;
抄送:&nbsp;"王帅帅"<1315975525@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ashnair1/dotadevkit] ModuleNotFoundError: No module named 'datasets.dotadevkit.ResultMerge_multi_process' (#7)





 
The dotadevkit does not have a train command just like the original DOTA Devkit did not have a train command.
 
The dev kit has 3 main functions:
  
Split the training data (images and labels) into tiles to train your model.
 
Merge the tiled results of your model.
 
Evaluate the merged detections against the val/test data and output a score.

**Comment by ashnair1** [comment]
No you cannot. There the code is using the original DOTA_Devkit. This package is optimised and structured differently. You will have to use the original for your application.

**Comment by s-s-wang** [comment]
> 
> 
> You can use this package as a replacement. But you'll have to make some changes.
> 
>     1. You have to replace the import statement [here](https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/e070d39bec96811378eb00a33d0e3969ed7be352/datasets/dataset_dota.py#L5), from
> 
> 
> `from .DOTA_devkit.ResultMerge_multi_process import mergebypoly`
> to
> `from dotadevkit.ops.ResultMerge import mergebypoly`
> 
>     1. Change this [line](https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/e070d39bec96811378eb00a33d0e3969ed7be352/datasets/dataset_dota.py#L123) to `mergebypoly(result_path, merge_path, 1, 0.3)`.
> 
> 
> This is because the mergebypoly function in the dotadevkit package takes two additional parameters: `num_processes` and `nms_threshold`. Refer [here](https://github.com/ashnair1/dotadevkit/blob/29d41910735a8367f4d2375755d96336e9cce1b9/dotadevkit/ops/ResultMerge.py#L257)

Thank you very much. According to your suggestion, there is a small problem, it report an error "....../datasets/dataset_hrsc.py, line 6, in <module> files  from .DOTA_devkit.hrsc_evaluation_task1 import voc_eval ModuleNotFoundError: No module named 'datasets.DOTA_devkit.hrsc_evaluation_task1'" after executing the training command.

**Comment by s-s-wang** [comment]
Thank you very much. After executive the train command in the BBAVectors-Oriented-Object-Detection-master file, it report error "RuntimeError: CUDA out of memory. Tried to allocate 182.00 MiB (GPU 0; 7.79 GiB total capacity; 6.52 GiB already allocated; 127.31 MiB free; 69.56 MiB cached)".




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ashnair1/dotadevkit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 凌晨4:06
收件人:&nbsp;"ashnair1/dotadevkit"<dotadevkit@noreply.github.com&gt;;
抄送:&nbsp;"王帅帅"<1315975525@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ashnair1/dotadevkit] ModuleNotFoundError: No module named 'datasets.dotadevkit.ResultMerge_multi_process' (#7)





 
Closed #7.

**Comment by s-s-wang** [comment]
> 
> 
> You can use this package as a replacement. But you'll have to make some changes.
> 
>     1. You have to replace the import statement [here](https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/e070d39bec96811378eb00a33d0e3969ed7be352/datasets/dataset_dota.py#L5), from
> 
> 
> `from .DOTA_devkit.ResultMerge_multi_process import mergebypoly`
> to
> `from dotadevkit.ops.ResultMerge import mergebypoly`
> 
>     1. Change this [line](https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/e070d39bec96811378eb00a33d0e3969ed7be352/datasets/dataset_dota.py#L123) to `mergebypoly(result_path, merge_path, 1, 0.3)`.
> 
> 
> This is because the mergebypoly function in the dotadevkit package takes two additional parameters: `num_processes` and `nms_threshold`. Refer [here](https://github.com/ashnair1/dotadevkit/blob/29d41910735a8367f4d2375755d96336e9cce1b9/dotadevkit/ops/ResultMerge.py#L257)

Thank you very much!

**Comment by s-s-wang** [comment]
> 
> 
> You can use this package as a replacement. But you'll have to make some changes.
> 
>     1. You have to replace the import statement [here](https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/e070d39bec96811378eb00a33d0e3969ed7be352/datasets/dataset_dota.py#L5), from
> 
> 
> `from .DOTA_devkit.ResultMerge_multi_process import mergebypoly`
> to
> `from dotadevkit.ops.ResultMerge import mergebypoly`
> 
>     1. Change this [line](https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/e070d39bec96811378eb00a33d0e3969ed7be352/datasets/dataset_dota.py#L123) to `mergebypoly(result_path, merge_path, 1, 0.3)`.
> 
> 
> This is because the mergebypoly function in the dotadevkit package takes two additional parameters: `num_processes` and `nms_threshold`. Refer [here](https://github.com/ashnair1/dotadevkit/blob/29d41910735a8367f4d2375755d96336e9cce1b9/dotadevkit/ops/ResultMerge.py#L257)

Can dotadevkit test the trained model and output text in the following format?
![图片](https://user-images.githubusercontent.com/74409617/100207243-56783e80-2f42-11eb-9177-153cdf4da42d.png)

**Comment by ashnair1** [comment]
`dotadevkit` can evaluate model results. Refer README [here](https://github.com/ashnair1/dotadevkit#evaluate).

**Comment by s-s-wang** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ashnair1/dotadevkit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 晚上8:37
收件人:&nbsp;"ashnair1/dotadevkit"<dotadevkit@noreply.github.com&gt;;
抄送:&nbsp;"王帅帅"<1315975525@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ashnair1/dotadevkit] ModuleNotFoundError: No module named 'datasets.dotadevkit.ResultMerge_multi_process' (#7)





 
dotadevkit can evaluate model results. Refer README here.
